-- MySQL Script generated by MySQL Workbench
-- Tue Jul 19 12:00:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema retail_store_morning
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `retail_store_morning` ;

-- -----------------------------------------------------
-- Schema retail_store_morning
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `retail_store_morning` DEFAULT CHARACTER SET utf8 ;
USE `retail_store_morning` ;

-- -----------------------------------------------------
-- Table `retail_store_morning`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_store_morning`.`Address` (
  `address_code` SMALLINT NOT NULL AUTO_INCREMENT,
  `public_place` VARCHAR(50) NOT NULL,
  `number_of_street` SMALLINT NOT NULL,
  `neighborhood` VARCHAR(50) NOT NULL,
  `city` VARCHAR(30) NOT NULL,
  `postal_code` CHAR(8) NOT NULL,
  PRIMARY KEY (`address_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retail_store_morning`.`Provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_store_morning`.`Provider` (
  `provider_code` SMALLINT NOT NULL AUTO_INCREMENT,
  `cnpj` CHAR(18) NOT NULL,
  `provider_name` VARCHAR(50) NOT NULL,
  `address_code` SMALLINT NOT NULL,
  PRIMARY KEY (`provider_code`),
  INDEX `fk_Provider_Address` (`address_code` ASC) ,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) ,
  CONSTRAINT `fk_Provider_Address`
    FOREIGN KEY (`address_code`)
    REFERENCES `retail_store_morning`.`Address` (`address_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retail_store_morning`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_store_morning`.`Product` (
  `product_code` SMALLINT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `product_price` DECIMAL(10,2) NOT NULL,
  `product_quantity` SMALLINT NOT NULL,
  `product_barcode` CHAR(13) NOT NULL,
  `product_active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`product_code`),
  UNIQUE INDEX `product_barcode_UNIQUE` (`product_barcode` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retail_store_morning`.`Provider_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_store_morning`.`Provider_Product` (
  `provider_code` SMALLINT NOT NULL,
  `product_code` SMALLINT NOT NULL,
  PRIMARY KEY (`provider_code`, `product_code`),
  INDEX `fk_Provider_has_Product_Product1_idx` (`product_code` ASC) ,
  INDEX `fk_Provider_has_Product_Provider1_idx` (`provider_code` ASC) ,
  CONSTRAINT `fk_Provider_has_Product_Provider1`
    FOREIGN KEY (`provider_code`)
    REFERENCES `retail_store_morning`.`Provider` (`provider_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Provider_has_Product_Product1`
    FOREIGN KEY (`product_code`)
    REFERENCES `retail_store_morning`.`Product` (`product_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
